CREATE TABLE AVALIACAO (
    ID SERIAL,
    NOTA INT NOT NULL,
    COMENTARIO VARCHAR(255),
    RESTAURANTE_ID BIGINT NOT NULL,
    USUARIO_ID BIGINT NOT NULL,
    CONSTRAINT AVALIACAO_PK PRIMARY KEY (ID),
    CONSTRAINT AVALIACAO_RESTAURANTE_FK FOREIGN KEY (RESTAURANTE_ID) REFERENCES RESTAURANTE(ID),
    CONSTRAINT AVALIACAO_USUARIO_FK FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(ID)
)