CREATE TABLE AVALIACAO (
    ID SERIAL,
    NOTA INT NOT NULL,
    COMENTARIO VARCHAR(255),
    RESTAURANTE VARCHAR(255) NOT NULL,
    USUARIO varchar(255) NOT NULL,
    CONSTRAINT AVALIACAO_PK PRIMARY KEY (ID)
)